# path to sample sheet relative to workflow folder
samples: config/samples.tsv

# distance parameters
distances:
  # maximum distance between junction points to be clustered together
  cluster: 10
  # minimum and maximum distance between nested contacts for the first pass
  # Changing it will require to recalculate most of the pipeline,
  # so select relaxed values here.
  nested_pass1:
    rmin: 10
    rmax: 100
  # minimum and maximum distance between nested contacts for the second pass. 
  # Should be stricter than the pass1 parameters
  nested_pass2:
    rmin: 20
    rmax: 50

# Contacts with read support less than or equal to this are removed
min_contact_support: 2
# options for PrePH structure prediction
#see [kalmSveta/PrePH](https://github.com/kalmSveta/PrePH#find-pairs-of-complementary-regions-in-two-sequences) for `fold.py` parameters description
preph_parameters: "-k 3 -a 3 -e -1 -u False -d 2"